name: Build wheel

on:
  workflow_dispatch:
    inputs:
      llvm-branch:
        description: The LLVM branch to release from
        type: string
        required: true
      version:
        description: The version number to release
        type: string
        required: true

jobs:
  build-linux:
    name: Build dist files (Linux)
    runs-on: [self-hosted, Linux]
    container:
      image: ubuntu:latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13, 3.14]

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get -y install clang cmake git lld

      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set version in pyproject.toml
        run: |
          sed -i 's/VERSION/"${{ inputs.version }}"/' pyproject.toml
          cat pyproject.toml

      - name: Clone LLVM
        uses: actions/checkout@v7
        with:
          repository: llvm/llvm-project
          path: llvm-project
          ref: ${{ inputs.llvm-branch }}

      - name: Build wheel
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: 8
          SKBUILD_CMAKE_SOURCE_DIR: llvm-project/llvm
          SKBUILD_CMAKE_ARGS: -DCMAKE_C_COMPILER=clang;-DCMAKE_CXX_COMPILER=clang++;-DLLVM_ENABLE_LLD=ON

        run: |
          pip install build
          python -m build --wheel --verbose .

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-linux-${{ matrix.python-version }}
          path: dist/

  build-macos:
    name: Build dist files (macOS)
    runs-on: [self-hosted, macOS]

    steps:
      - name: Install system dependencies
        run: |
          brew install lld python

      - uses: actions/checkout@v7

      - name: Set version in pyproject.toml
        run: |
          : # Note that the sed command is different to the Linux one because
          : # macOS sed is slightly different
          sed -iE 's/VERSION/"${{ inputs.version }}"/' pyproject.toml
          cat pyproject.toml

      - name: Clone LLVM
        uses: actions/checkout@v7
        with:
          repository: llvm/llvm-project
          path: llvm-project
          ref: ${{ inputs.llvm-branch }}

      - name: Build wheel
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: 4
          SKBUILD_CMAKE_SOURCE_DIR: llvm-project/llvm
          SKBUILD_CMAKE_ARGS: -DCMAKE_C_COMPILER=clang;-DCMAKE_CXX_COMPILER=clang++;-DLLVM_ENABLE_LLD=ON

        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install build
          python -m build --wheel --verbose .

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-macos
          path: dist/

  github_release:
    name: Create GitHub release
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8
        with:
          pattern: dist-*
          path: dist/
          merge-multiple: true

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ "$( gh release view ${{ inputs.version }} )" ]; then
            : # version exists
            gh release upload --clobber ${{ inputs.version }} dist/*
          else
            : # version does not exist
            gh release create --title ${{ inputs.version }} ${{ inputs.version }} dist/*
          fi
